const fs = require('fs');
const os = require('os');
const path = require('path');
const { withAppBuildGradle } = require('expo/config-plugins');

// The Wearable Data Layer only routes between apps that share an applicationId AND a signing
// certificate. Both halves are `app.wolfset`, but left alone they sign with different keys:
// the Expo/RN template ships its own android/app/debug.keystore, while the watch app (wear/)
// uses the machine-wide ~/.android/debug.keystore that AGP picks by default. Same package,
// different cert — every message is dropped silently, on both sides, which reads exactly
// like "the pipe doesn't work" (learned the hard way in the Phase 0 spike).
//
// Point the phone app's debug signingConfig at ~/.android/debug.keystore so both match.
// android/ is regenerated by prebuild, so this has to be a plugin rather than a hand edit.
// Release builds are unaffected; production signing is decided with store submission.

const TEMPLATE_STORE_FILE = "storeFile file('debug.keystore')";
const SHARED_STORE_FILE =
  "storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')";

module.exports = function withSharedDebugKeystore(config) {
  return withAppBuildGradle(config, (cfg) => {
    const keystore = path.join(os.homedir(), '.android', 'debug.keystore');
    if (!fs.existsSync(keystore)) {
      throw new Error(
        `withSharedDebugKeystore: ${keystore} does not exist.\n` +
          'The watch and phone apps must share a signing cert or the Data Layer will not ' +
          'route. Create it with:\n' +
          `  keytool -genkeypair -v -keystore ${keystore} -storepass android \\\n` +
          '    -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 ' +
          '-validity 10000 \\\n    -dname "CN=Android Debug,O=Android,C=US"',
      );
    }

    const { contents } = cfg.modResults;
    if (!contents.includes(TEMPLATE_STORE_FILE)) {
      // Fail loudly: silently leaving the template keystore in place reintroduces the exact
      // cert mismatch this plugin exists to prevent.
      if (contents.includes(SHARED_STORE_FILE)) return cfg;
      throw new Error(
        `withSharedDebugKeystore: could not find ${TEMPLATE_STORE_FILE} in app/build.gradle. ` +
          'The Expo template changed — update this plugin, and re-verify both APKs report the ' +
          'same signer via `apksigner verify --print-certs`.',
      );
    }

    cfg.modResults.contents = contents.replace(TEMPLATE_STORE_FILE, SHARED_STORE_FILE);
    return cfg;
  });
};
