plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.wolfset.hr'
version = '0.1.0'

android {
  namespace "app.wolfset.hr"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // The Wearable Data Layer: WearableListenerService + MessageEvent.
  implementation 'com.google.android.gms:play-services-wearable:19.0.0'
}
