plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.wolfset.spike.hrmodule'
version = '0.1.0'

android {
  namespace "app.wolfset.spike.hrmodule"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.google.android.gms:play-services-wearable:19.0.0'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0'
}
