const fs = require('fs');
const os = require('os');
const path = require('path');
const { withAppBuildGradle } = require('expo/config-plugins');

// The Wearable Data Layer only routes between apps that share an applicationId AND a signing
// certificate. Both halves of this spike are app.wolfset.spike, but they were signing with
// different keys: the Expo/RN template ships its own android/app/debug.keystore, while the
// watch app (spike-hr/wear) uses the machine-wide ~/.android/debug.keystore that AGP picks by
// default. Same package, different cert — messages are dropped silently, with no error on
// either side, which reads exactly like "the pipe doesn't work" and would fail the Phone 0
// gate for a reason that has nothing to do with the pipe.
//
// Point the phone app's debug signingConfig at ~/.android/debug.keystore so both match.
// android/ is regenerated by prebuild, so this has to be a plugin rather than a hand edit.

const TEMPLATE_STORE_FILE = "storeFile file('debug.keystore')";
const SHARED_STORE_FILE =
  "storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')";

module.exports = function withSharedDebugKeystore(config) {
  return withAppBuildGradle(config, (cfg) => {
    const keystore = path.join(os.homedir(), '.android', 'debug.keystore');
    if (!fs.existsSync(keystore)) {
      throw new Error(
        `withSharedDebugKeystore: ${keystore} does not exist.\n` +
          'The watch and phone apps must share a signing cert or the Data Layer will not ' +
          'route. Create it with:\n' +
          `  keytool -genkeypair -v -keystore ${keystore} -storepass android \\\n` +
          '    -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 ' +
          '-validity 10000 \\\n    -dname "CN=Android Debug,O=Android,C=US"',
      );
    }

    const { contents } = cfg.modResults;
    if (!contents.includes(TEMPLATE_STORE_FILE)) {
      // Fail loudly: silently leaving the template keystore in place reintroduces the exact
      // cert mismatch this plugin exists to prevent.
      if (contents.includes(SHARED_STORE_FILE)) return cfg;
      throw new Error(
        `withSharedDebugKeystore: could not find ${TEMPLATE_STORE_FILE} in app/build.gradle. ` +
          'The Expo template changed — update this plugin, and re-verify both APKs report the ' +
          'same signer via `apksigner verify --print-certs`.',
      );
    }

    cfg.modResults.contents = contents.replace(TEMPLATE_STORE_FILE, SHARED_STORE_FILE);
    return cfg;
  });
};
